# This file allows packrat (used by rsconnect during deployment) to pick up dependencies.
library(dplyr)
library(htmltools)
library(nblR)
library(plotly)
library(reactable)
library(rhino)
library(shiny.router)
library(shiny.semantic)
library(stringr)
library(tidyr)
library(treesitter)
library(treesitter.r)
